name: Manually triggering workflows (with input parameters)
run-name: ${{ github.actor }} is running this manual '${{ github.event_name }}' event trigger workflow!

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        type: string
      greeting:
        description: "Type of greeting"
        required: true
        type: string
      secret-word:
        description: "Super secret word which we are going to encrypt"
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Encode our super secret word
        run: |
          ENCODED=$(echo "${{ inputs.secret-word }}" | base64)
          echo "SECRET_WORD=$ENCODED" >> "$GITHUB_ENV"
      - name: Display Greeting
        run: |
          echo "${{ inputs.greeting }}, ${{ inputs.name }}!"
      - name: Display the super secret word after encoding
        run: |
          echo "Super secret word encoding:"
          echo "Encoded super secret word is: $SECRET_WORD"
      - name: Decode super secret word
        run: |
          echo "$SECRET_WORD" | base64 --decode
