name: Setting Custom Environment Variables
run-name: ${{ github.actor }} is setting custom env vars at different workflow levels.

on:
  workflow_dispatch:

# Workflow-level variable - can use this variable in the entire workflow
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    # Job-level variable - can be used across this job only
    env:
      Greeting: Hello

    steps:
      - name: "Say Hello ${{ github.actor }}, it's Monday!"
        run: |
          echo "$Greeting $First_Name". Today is $DAY_OF_WEEK!"
        # Step-level: only usable IN THIS STEP only
        env:
          First_Name: Travis
      - name: "Saying Hello only if it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday'}} # accessing the variable using the `env` context object instead
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK, it is NOT Tuesday!"
        env:
          First_Name: Pablo
          Greeting: "${{ env.GREETING }} and Hola"
