name: Manually trigger workflows with inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        type: string
      greeting:
        description: "The greeting used to greet the person"
        required: false
        default: "Hello"
        type: string
      data:
        description: "Base64 encoded content of a file"
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print the greeting
        run: |
          echo "${{ inputs.greeting }}, ${{ inputs.name }}!"

      - name: Decode the file contents
        run: |
          echo "${{ inputs.data }}" | base64 --decode > ./decoded_file.txt

      - name: Display file contents
        run: |
          echo "Contents of the file:"
          cat ./decoded_file.txt
